# Generated by Django 6.0.7 on 2026-07-22 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_salao', models.CharField(default='Salão de Beleza', max_length=100, verbose_name='Nome do salão')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('morada', models.CharField(blank=True, max_length=200, verbose_name='Morada')),
                ('hora_abertura', models.TimeField(default=datetime.time(9, 0), verbose_name='Hora de abertura')),
                ('hora_fecho', models.TimeField(default=datetime.time(19, 0), verbose_name='Hora de fecho')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
