# Generated by Django 6.0.7 on 2026-07-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='fuso_horario',
            field=models.CharField(choices=[('Europa', [('Europe/Lisbon', 'Lisboa (Portugal)'), ('Europe/Madrid', 'Madrid (Espanha)'), ('Europe/Paris', 'Paris (França)'), ('Europe/London', 'Londres (Reino Unido)')]), ('África', [('Africa/Casablanca', 'Casablanca (Marrocos)'), ('Africa/Lagos', 'Lagos (Nigéria)'), ('Africa/Cairo', 'Cairo (Egito)'), ('Africa/Johannesburg', 'Joanesburgo (África do Sul)')]), ('América', [('America/Sao_Paulo', 'São Paulo (Brasil)'), ('America/New_York', 'Nova Iorque (EUA)'), ('America/Mexico_City', 'Cidade do México (México)'), ('America/Argentina/Buenos_Aires', 'Buenos Aires (Argentina)')]), ('Ásia', [('Asia/Dubai', 'Dubai (Emirados)'), ('Asia/Kolkata', 'Bombaim (Índia)'), ('Asia/Shanghai', 'Xangai (China)'), ('Asia/Tokyo', 'Tóquio (Japão)')]), ('Oceânia', [('Australia/Sydney', 'Sydney (Austrália)'), ('Pacific/Auckland', 'Auckland (Nova Zelândia)')])], default='Europe/Lisbon', max_length=40, verbose_name='Fuso horário'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='idioma',
            field=models.CharField(choices=[('pt-pt', 'Português (Portugal)'), ('es', 'Español'), ('en', 'English'), ('fr', 'Français')], default='pt-pt', max_length=5, verbose_name='Idioma'),
        ),
    ]
