# Generated by Django 6.0.7 on 2026-07-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('funcao', models.CharField(blank=True, max_length=80, verbose_name='Função')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('servicos', models.ManyToManyField(blank=True, to='servicos.servico', verbose_name='Serviços que presta')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
    ]
