# Generated by Django 6.0.7 on 2026-07-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_utilizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='funcionarios/', verbose_name='Fotografia'),
        ),
    ]
