# Generated by Django 6.0.7 on 2026-07-23 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_funcionario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AusenciaFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('folga', 'Folga'), ('ferias', 'Férias'), ('doenca', 'Doença'), ('outro', 'Outro')], default='folga', max_length=20, verbose_name='Tipo de ausência')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(verbose_name='Data de fim')),
                ('dia_inteiro', models.BooleanField(default=True, verbose_name='Dia inteiro')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de início')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='Hora de fim')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='Motivo ou observação')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Ausência do funcionário',
                'verbose_name_plural': 'Ausências dos funcionários',
                'ordering': ['-data_inicio', 'funcionario__nome'],
            },
        ),
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de entrada')),
                ('hora_fim', models.TimeField(verbose_name='Hora de saída')),
                ('intervalo_inicio', models.TimeField(blank=True, null=True, verbose_name='Início do intervalo')),
                ('intervalo_fim', models.TimeField(blank=True, null=True, verbose_name='Fim do intervalo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Trabalha neste dia')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Horário de trabalho',
                'verbose_name_plural': 'Horários de trabalho',
                'ordering': ['funcionario__nome', 'dia_semana'],
                'constraints': [models.UniqueConstraint(fields=('funcionario', 'dia_semana'), name='horario_unico_por_funcionario_dia')],
            },
        ),
    ]
