# Generated by Django 6.0.7 on 2026-07-20 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('funcionarios', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='Data e hora')),
                ('estado', models.CharField(choices=[('marcada', 'Marcada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('faltou', 'Faltou')], default='marcada', max_length=10, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marcacoes', to='clientes.cliente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marcacoes', to='funcionarios.funcionario')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marcacoes', to='servicos.servico')),
            ],
            options={
                'verbose_name': 'Marcação',
                'verbose_name_plural': 'Marcações',
                'ordering': ['inicio'],
            },
        ),
    ]
