# Generated by Django 6.0.7 on 2026-07-20 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('funcionarios', '0001_initial'),
        ('marcacoes', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='Número')),
                ('descricao', models.CharField(blank=True, max_length=80, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Posto',
                'verbose_name_plural': 'Postos',
                'ordering': ['numero'],
            },
        ),
        migrations.AlterField(
            model_name='marcacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marcacoes', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='marcacao',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marcacoes', to='funcionarios.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='marcacao',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marcacoes', to='servicos.servico', verbose_name='Serviço'),
        ),
        migrations.AddField(
            model_name='marcacao',
            name='posto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marcacoes', to='marcacoes.posto', verbose_name='Mesa / Posto'),
        ),
    ]
