"""
Django settings for salao project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path


# Build paths inside the project like this:
# BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings
# Unsuitable for production.

SECRET_KEY = (
    "django-insecure-vi!qihx5vrg3^%s9yhzcai@w!"
    "#9)p&x#1yrg%$(fnldmvw2jea"
)

DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "clientes",
    "servicos",
    "utilizadores",
    "funcionarios",
    "marcacoes",
    "relatorios",
    "mapa",
    "configuracoes",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "configuracoes.middleware.ConfiguracaoMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "salao.urls"


TEMPLATES = [
    {
        "BACKEND": (
            "django.template.backends.django."
            "DjangoTemplates"
        ),
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                (
                    "django.template.context_processors."
                    "request"
                ),
                (
                    "django.contrib.auth."
                    "context_processors.auth"
                ),
                (
                    "django.contrib.messages."
                    "context_processors.messages"
                ),
                (
                    "configuracoes.context_processors."
                    "configuracao"
                ),
                (
                    "utilizadores.context_processors."
                    "permissoes_utilizador"
                ),
                (
                    "marcacoes.context_processors."
                    "pendentes_antigas"
                ),
            ],
        },
    },
]


WSGI_APPLICATION = "salao.wsgi.application"


# Database

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "salao_beleza",
        "USER": "salao",
        "PASSWORD": "salao2026",
        "HOST": "127.0.0.1",
        "PORT": "3306",
    }
}


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# Internationalization

LANGUAGE_CODE = "pt-pt"

TIME_ZONE = "Europe/Lisbon"

USE_I18N = True

USE_TZ = True


LANGUAGES = [
    ("pt-pt", "Português"),
    ("es", "Español"),
    ("en", "English"),
    ("fr", "Français"),
]


LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static and uploaded files

STATIC_URL = "static/"

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# Authentication

LOGIN_URL = "/contas/login/"

LOGIN_REDIRECT_URL = "/"

LOGOUT_REDIRECT_URL = "/contas/login/"